DROP DATABASE IF EXISTS shop;
CREATE DATABASE shop;
USE shop;

CREATE TABLE HOUSE (
    HOUSE_ID SERIAL UNIQUE,
    IMAGE VARCHAR(255) NOT NULL,
    CREATEDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    POSTALCODE VARCHAR(225) NOT NULL,
    PRIMARY KEY (HOUSE_ID)
);

CREATE TABLE APARTMENT (
    APARTMENT_ID SERIAL,
    IMAGE VARCHAR(255),
    CREATEDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRICE DOUBLE NOT NULL,
    NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    STATE VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    POSTALCODE VARCHAR(225) NOT NULL,
    AVAILABILITY BOOLEAN NOT NULL,
    HOUSE_ID BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (APARTMENT_ID),
    FOREIGN KEY (HOUSE_ID) REFERENCES HOUSE(HOUSE_ID)
);

CREATE TABLE ADMIN (
    ADMIN_ID SERIAL UNIQUE,
    U_NAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY (ADMIN_ID)
);

insert into ADMIN (ADMIN_ID, U_NAME, PASSWORD)
values (1, 'Omega', 'omega');

insert into HOUSE (IMAGE, NAME, DESCRIPTION, ADDRESS, CITY, STATE, COUNTRY, POSTALCODE)
values ('1_1.jpg', 'H1','House 1', 'Stettbachstrasse 129g', 'Zuerich', 'Zuerich', 'Switzerland', '8051'),
('2_1.jpg', 'H2','House 2', 'asdf 5', 'qwer', 'yxcv', 'zuio', '7890'),
('3_1.jpg', 'H3','House 3', 'Zuerichstrasse 1a', 'Zuerich', 'Zuerich', 'Switzerland', '8000');

insert into APARTMENT (IMAGE, PRICE, NAME, DESCRIPTION, ADDRESS, CITY, STATE, COUNTRY, POSTALCODE, AVAILABILITY, HOUSE_ID)
values ('1_2.jpg', 1000 , 'A1','Apartment 1', 'Stettbachstrasse 129g', 'Zuerich', 'Zuerich', 'Switzerland', '8051', 'true', 1),
('2_2.jpg', 2000 , 'A2', 'Apartment 2', 'asdf 5', 'qwer', 'yxcv', 'zuio', '7890', 'true', 2),
('3_2.jpg', 3000 , 'A3', 'Apartment 3', 'Zuerichstrasse 1a', 'Zuerich', 'Zuerich', 'Switzerland', '8000', 'true', 3);


